#!/usr/bin/env bash
# installs nginx server

sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=JKxlsvZXG7c;}' /etc/nginx/sites-available/default
sudo service nginx restart
