#!/usr/bin/env bash
# Add custom header to nginx configuration to return hostname

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "24i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
