#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt -y update
sudo apt-get -y install haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "
frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web-01 52.91.131.155:80 check
        server web-02 34.207.188.100:80 check
" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
