#!/usr/bin/env bash
#This script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

q=1
while [ $q -le 10 ];
do
  if [ $q -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((q++))
done
